# Generated by Django 2.2.2 on 2019-07-27 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ViajeroFrecuente', '0006_auto_20190630_0111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='trip_tripstatus',
        ),
    ]
