# Generated by Django 2.2.2 on 2019-07-28 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ViajeroFrecuente', '0008_auto_20190728_0754'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qualification',
            old_name='qualification_comments',
            new_name='comments',
        ),
        migrations.RenameField(
            model_name='qualification',
            old_name='qualification_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='qualification',
            old_name='qualification_value',
            new_name='givenvalue',
        ),
        migrations.RenameField(
            model_name='qualification',
            old_name='qualification_trip',
            new_name='trip',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='trip_amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='trip_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='trip_from',
            new_name='fromPlace',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='trip_passengerqty',
            new_name='passengerqty',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='trip_to',
            new_name='toPlace',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='trip_vehicle',
            new_name='vehicle',
        ),
        migrations.RenameField(
            model_name='tripstatus',
            old_name='tripstatus_description',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='trip_driver',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='trip_passengers',
        ),
        migrations.AddField(
            model_name='qualification',
            name='givenby',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='givenby', to='ViajeroFrecuente.AppUser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qualification',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='userqual', to='ViajeroFrecuente.AppUser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='driver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='driver', to='ViajeroFrecuente.AppUser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='passengers',
            field=models.ManyToManyField(related_name='passengers', to='ViajeroFrecuente.AppUser'),
        ),
        migrations.AlterUniqueTogether(
            name='qualification',
            unique_together={('trip', 'user', 'givenby')},
        ),
        migrations.RemoveField(
            model_name='qualification',
            name='qualification_givenby',
        ),
        migrations.RemoveField(
            model_name='qualification',
            name='qualification_user',
        ),
    ]
