# Generated by Django 2.2.2 on 2019-07-28 20:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ViajeroFrecuente', '0014_auto_20190728_1758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appuser',
            old_name='user',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='qualification',
            name='givenby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='givenby', to='ViajeroFrecuente.AppUser', to_field='user'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userqual', to='ViajeroFrecuente.AppUser', to_field='user'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 28, 17, 58, 59, 535731)),
        ),
        migrations.AlterField(
            model_name='trip',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver', to='ViajeroFrecuente.AppUser', to_field='user'),
        ),
    ]
