# Generated by Django 2.2.2 on 2019-07-29 00:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ViajeroFrecuente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 28, 21, 45, 40, 263482)),
        ),
    ]
